<a href="https://colab.research.google.com/github/GraceChen996/TensorFlowLearningNote/blob/branch1/Tensorflow%E5%B8%B8%E8%A7%81%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

# 矩阵乘法

In [22]:
#矩阵乘法运算
a=[[1]]
b=[[1]]
m=tf.linalg.matmul(a,b) #将矩阵a和矩阵b相乘，返回a*b

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]], dtype=int32)>

# constant

In [32]:
#从一个张量类型创建一个常量类型
'''tf.constant(
#    value, dtype=None, shape=None, name='Const'
#)
'''
x1 = tf.constant([1,2,3,4,5,6],dtype='float32') #数据类型转换
print(x1)
x2 = tf.constant([1,2,3,4,5,6],shape=(2,3)) #张量格式转换
print(x2)

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


# 格式转换

In [40]:
x1.numpy() #将张量转换成numpy格式
x1

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [38]:
'''
tf.cast(
    x, dtype, name=None
)
'''
x1 = tf.cast(x1,tf.int32) #将浮点类型的张量又转成了int类型
print(x1)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [3]:
'''
numpy.multiply(
  x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]
)
'''
x = np.ones([2,2])
print(x)
x = tf.multiply(x,2)
print(x)

[[1. 1.]
 [1. 1.]]
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)
